services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://admin:password@localhost:27017/admin", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mongodb_data: